# Generated by Django 4.2.6 on 2024-11-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatinvitation_room_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinvitation',
            name='room_data',
        ),
    ]
