# Generated by Django 4.2.6 on 2024-11-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_chatinvitation_room_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatinvitation',
            unique_together=set(),
        ),
    ]
