# Generated by Django 4.2.6 on 2025-01-26 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(help_text='Introduce your avatar name', max_length=15)),
                ('avatar', models.FileField(blank=True, upload_to='avatars')),
                ('connections', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('accepter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepter', to='userManagement.profile')),
                ('giver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giver', to='userManagement.profile')),
            ],
        ),
    ]
